[package]
name = "redstoneware"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
cipher = "0.4.4"
dirs = "4.0.0"
futures = "0.3.27"
orion = "0.17.4"
rand = "0.8.5"
